### ISSUE TITLE
Consider changing default branch to v3

### ISSUE THREAD

**Issue by TechplexEngineer** [PlasmaRobotics2403/TBA-PythonAPI#8]
I thought this project was dead until I saw that there were recent publishes to pypi.

Might be nice to change the default branch to v3 where the current work seems to be occurring.
![Selection_110](https://user-images.githubusercontent.com/175873/56101907-8c47eb00-5ef6-11e9-93a5-142fd7afc66e.png)

**Comment by TechplexEngineer** [comment]
@nardavin Any chance you could share why not?

**Comment by nardavin** [comment]
Sorry, thought I left a message. For all purposes this repo is dead. It may be back in a year or so, but the main collaborator is currently unable to work on the project. To my understanding, the v3 branch was not left in a finished state, so I'm not sure it would be a good idea to have that branch be main.

**Comment by devyntk** [comment]
For the record, @octocynth and I were left in charge of this repo when @ThePlasmaGuy left. He'll return again in September. This repository (specifically the v3 branch) used to be the TBA library for FRCDiscord/Dozer, however we recently switched to guineawheek/aiotba. I entirely agree that this library is dead, and you should seek other options, or continue work on a more complete substitution, unless you have much of a reason to continue work on this repo.

**Comment by TechplexEngineer** [comment]
Thanks much for the update. I just found https://github.com/frc1418/tbapy I'll give that a go.
